apiVersion: apps/v1
kind: Deployment
metadata:
  name: courses-api
spec:
  selector:
    matchLabels:
      app: courses-api
  template:
    metadata:
      labels:
        app: courses-api
    spec:
      containers:
      - name: courses-api
        image: courses-api
        ports:
        - containerPort: 8080
